//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestComModel.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JSON_OBJ", Namespace="http://schemas.datacontract.org/2004/07/ComModelService")]
    [System.SerializableAttribute()]
    public partial class JSON_OBJ : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JSON_OBJECTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OBJECT_TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JSON_OBJECT {
            get {
                return this.JSON_OBJECTField;
            }
            set {
                if ((object.ReferenceEquals(this.JSON_OBJECTField, value) != true)) {
                    this.JSON_OBJECTField = value;
                    this.RaisePropertyChanged("JSON_OBJECT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OBJECT_Type {
            get {
                return this.OBJECT_TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.OBJECT_TypeField, value) != true)) {
                    this.OBJECT_TypeField = value;
                    this.RaisePropertyChanged("OBJECT_Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/ComModelService")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JSON_ResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JSON_Response {
            get {
                return this.JSON_ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.JSON_ResponseField, value) != true)) {
                    this.JSON_ResponseField = value;
                    this.RaisePropertyChanged("JSON_Response");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IComModelService")]
    public interface IComModelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/Login", ReplyAction="http://tempuri.org/IComModelService/LoginResponse")]
        TestComModel.ServiceReference1.LoginResponse Login(TestComModel.ServiceReference1.LoginRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/Login", ReplyAction="http://tempuri.org/IComModelService/LoginResponse")]
        System.Threading.Tasks.Task<TestComModel.ServiceReference1.LoginResponse> LoginAsync(TestComModel.ServiceReference1.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/GetObjectByKey", ReplyAction="http://tempuri.org/IComModelService/GetObjectByKeyResponse")]
        TestComModel.ServiceReference1.JSON_OBJ GetObjectByKey(string Key, string ObjType, string SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/GetObjectByKey", ReplyAction="http://tempuri.org/IComModelService/GetObjectByKeyResponse")]
        System.Threading.Tasks.Task<TestComModel.ServiceReference1.JSON_OBJ> GetObjectByKeyAsync(string Key, string ObjType, string SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/GetObjectBulk", ReplyAction="http://tempuri.org/IComModelService/GetObjectBulkResponse")]
        TestComModel.ServiceReference1.JSON_OBJ GetObjectBulk(string FieldName, string FieldValue, string ObjType, string SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/GetObjectBulk", ReplyAction="http://tempuri.org/IComModelService/GetObjectBulkResponse")]
        System.Threading.Tasks.Task<TestComModel.ServiceReference1.JSON_OBJ> GetObjectBulkAsync(string FieldName, string FieldValue, string ObjType, string SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/GetObjectBulkonDate", ReplyAction="http://tempuri.org/IComModelService/GetObjectBulkonDateResponse")]
        TestComModel.ServiceReference1.JSON_OBJ GetObjectBulkonDate(string FieldName, string FieldValue, string StartDate, string EndDate, string ObjType, string SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/GetObjectBulkonDate", ReplyAction="http://tempuri.org/IComModelService/GetObjectBulkonDateResponse")]
        System.Threading.Tasks.Task<TestComModel.ServiceReference1.JSON_OBJ> GetObjectBulkonDateAsync(string FieldName, string FieldValue, string StartDate, string EndDate, string ObjType, string SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/AddUpdateObject", ReplyAction="http://tempuri.org/IComModelService/AddUpdateObjectResponse")]
        TestComModel.ServiceReference1.Response AddUpdateObject(TestComModel.ServiceReference1.JSON_OBJ Object, string SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/AddUpdateObject", ReplyAction="http://tempuri.org/IComModelService/AddUpdateObjectResponse")]
        System.Threading.Tasks.Task<TestComModel.ServiceReference1.Response> AddUpdateObjectAsync(TestComModel.ServiceReference1.JSON_OBJ Object, string SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/LogOut", ReplyAction="http://tempuri.org/IComModelService/LogOutResponse")]
        bool LogOut(string SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/LogOut", ReplyAction="http://tempuri.org/IComModelService/LogOutResponse")]
        System.Threading.Tasks.Task<bool> LogOutAsync(string SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/GetObjectKeys", ReplyAction="http://tempuri.org/IComModelService/GetObjectKeysResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Response")]
        TestComModel.ServiceReference1.Response GetObjectKeys(string ObjType, string SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/GetObjectKeys", ReplyAction="http://tempuri.org/IComModelService/GetObjectKeysResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Response")]
        System.Threading.Tasks.Task<TestComModel.ServiceReference1.Response> GetObjectKeysAsync(string ObjType, string SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/GetObjectKeysFilter", ReplyAction="http://tempuri.org/IComModelService/GetObjectKeysFilterResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Response")]
        TestComModel.ServiceReference1.Response GetObjectKeysFilter(string ObjType, string FieldName, string FieldValue, string SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/GetObjectKeysFilter", ReplyAction="http://tempuri.org/IComModelService/GetObjectKeysFilterResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Response")]
        System.Threading.Tasks.Task<TestComModel.ServiceReference1.Response> GetObjectKeysFilterAsync(string ObjType, string FieldName, string FieldValue, string SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/DoQuery", ReplyAction="http://tempuri.org/IComModelService/DoQueryResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="responses")]
        TestComModel.ServiceReference1.Response DoQuery(string Query, string SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/DoQuery", ReplyAction="http://tempuri.org/IComModelService/DoQueryResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="responses")]
        System.Threading.Tasks.Task<TestComModel.ServiceReference1.Response> DoQueryAsync(string Query, string SessionID);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        public LoginRequest() {
        }
        
        public LoginRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string SessionID;
        
        public LoginResponse() {
        }
        
        public LoginResponse(string Message, string SessionID) {
            this.Message = Message;
            this.SessionID = SessionID;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IComModelServiceChannel : TestComModel.ServiceReference1.IComModelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComModelServiceClient : System.ServiceModel.ClientBase<TestComModel.ServiceReference1.IComModelService>, TestComModel.ServiceReference1.IComModelService {
        
        public ComModelServiceClient() {
        }
        
        public ComModelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComModelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComModelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComModelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestComModel.ServiceReference1.LoginResponse TestComModel.ServiceReference1.IComModelService.Login(TestComModel.ServiceReference1.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string username, string password, out string SessionID) {
            TestComModel.ServiceReference1.LoginRequest inValue = new TestComModel.ServiceReference1.LoginRequest();
            inValue.username = username;
            inValue.password = password;
            TestComModel.ServiceReference1.LoginResponse retVal = ((TestComModel.ServiceReference1.IComModelService)(this)).Login(inValue);
            SessionID = retVal.SessionID;
            return retVal.Message;
        }
        
        public System.Threading.Tasks.Task<TestComModel.ServiceReference1.LoginResponse> LoginAsync(TestComModel.ServiceReference1.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public TestComModel.ServiceReference1.JSON_OBJ GetObjectByKey(string Key, string ObjType, string SessionID) {
            return base.Channel.GetObjectByKey(Key, ObjType, SessionID);
        }
        
        public System.Threading.Tasks.Task<TestComModel.ServiceReference1.JSON_OBJ> GetObjectByKeyAsync(string Key, string ObjType, string SessionID) {
            return base.Channel.GetObjectByKeyAsync(Key, ObjType, SessionID);
        }
        
        public TestComModel.ServiceReference1.JSON_OBJ GetObjectBulk(string FieldName, string FieldValue, string ObjType, string SessionID) {
            return base.Channel.GetObjectBulk(FieldName, FieldValue, ObjType, SessionID);
        }
        
        public System.Threading.Tasks.Task<TestComModel.ServiceReference1.JSON_OBJ> GetObjectBulkAsync(string FieldName, string FieldValue, string ObjType, string SessionID) {
            return base.Channel.GetObjectBulkAsync(FieldName, FieldValue, ObjType, SessionID);
        }
        
        public TestComModel.ServiceReference1.JSON_OBJ GetObjectBulkonDate(string FieldName, string FieldValue, string StartDate, string EndDate, string ObjType, string SessionID) {
            return base.Channel.GetObjectBulkonDate(FieldName, FieldValue, StartDate, EndDate, ObjType, SessionID);
        }
        
        public System.Threading.Tasks.Task<TestComModel.ServiceReference1.JSON_OBJ> GetObjectBulkonDateAsync(string FieldName, string FieldValue, string StartDate, string EndDate, string ObjType, string SessionID) {
            return base.Channel.GetObjectBulkonDateAsync(FieldName, FieldValue, StartDate, EndDate, ObjType, SessionID);
        }
        
        public TestComModel.ServiceReference1.Response AddUpdateObject(TestComModel.ServiceReference1.JSON_OBJ Object, string SessionID) {
            return base.Channel.AddUpdateObject(Object, SessionID);
        }
        
        public System.Threading.Tasks.Task<TestComModel.ServiceReference1.Response> AddUpdateObjectAsync(TestComModel.ServiceReference1.JSON_OBJ Object, string SessionID) {
            return base.Channel.AddUpdateObjectAsync(Object, SessionID);
        }
        
        public bool LogOut(string SessionID) {
            return base.Channel.LogOut(SessionID);
        }
        
        public System.Threading.Tasks.Task<bool> LogOutAsync(string SessionID) {
            return base.Channel.LogOutAsync(SessionID);
        }
        
        public TestComModel.ServiceReference1.Response GetObjectKeys(string ObjType, string SessionID) {
            return base.Channel.GetObjectKeys(ObjType, SessionID);
        }
        
        public System.Threading.Tasks.Task<TestComModel.ServiceReference1.Response> GetObjectKeysAsync(string ObjType, string SessionID) {
            return base.Channel.GetObjectKeysAsync(ObjType, SessionID);
        }
        
        public TestComModel.ServiceReference1.Response GetObjectKeysFilter(string ObjType, string FieldName, string FieldValue, string SessionID) {
            return base.Channel.GetObjectKeysFilter(ObjType, FieldName, FieldValue, SessionID);
        }
        
        public System.Threading.Tasks.Task<TestComModel.ServiceReference1.Response> GetObjectKeysFilterAsync(string ObjType, string FieldName, string FieldValue, string SessionID) {
            return base.Channel.GetObjectKeysFilterAsync(ObjType, FieldName, FieldValue, SessionID);
        }
        
        public TestComModel.ServiceReference1.Response DoQuery(string Query, string SessionID) {
            return base.Channel.DoQuery(Query, SessionID);
        }
        
        public System.Threading.Tasks.Task<TestComModel.ServiceReference1.Response> DoQueryAsync(string Query, string SessionID) {
            return base.Channel.DoQueryAsync(Query, SessionID);
        }
    }
}
