//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JSON_OBJ", Namespace="http://schemas.datacontract.org/2004/07/ComModel")]
    [System.SerializableAttribute()]
    public partial class JSON_OBJ : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JSON_OBJECTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OBJECT_TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JSON_OBJECT {
            get {
                return this.JSON_OBJECTField;
            }
            set {
                if ((object.ReferenceEquals(this.JSON_OBJECTField, value) != true)) {
                    this.JSON_OBJECTField = value;
                    this.RaisePropertyChanged("JSON_OBJECT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OBJECT_Type {
            get {
                return this.OBJECT_TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.OBJECT_TypeField, value) != true)) {
                    this.OBJECT_TypeField = value;
                    this.RaisePropertyChanged("OBJECT_Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/ComModel")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JSON_ResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JSON_Response {
            get {
                return this.JSON_ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.JSON_ResponseField, value) != true)) {
                    this.JSON_ResponseField = value;
                    this.RaisePropertyChanged("JSON_Response");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IComModelService")]
    public interface IComModelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/Login", ReplyAction="http://tempuri.org/IComModelService/LoginResponse")]
        Test.ServiceReference1.LoginResponse Login(Test.ServiceReference1.LoginRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/Login", ReplyAction="http://tempuri.org/IComModelService/LoginResponse")]
        System.Threading.Tasks.Task<Test.ServiceReference1.LoginResponse> LoginAsync(Test.ServiceReference1.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/SignIn", ReplyAction="http://tempuri.org/IComModelService/SignInResponse")]
        Test.ServiceReference1.SignInResponse SignIn(Test.ServiceReference1.SignInRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/SignIn", ReplyAction="http://tempuri.org/IComModelService/SignInResponse")]
        System.Threading.Tasks.Task<Test.ServiceReference1.SignInResponse> SignInAsync(Test.ServiceReference1.SignInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/GetObjectByKey", ReplyAction="http://tempuri.org/IComModelService/GetObjectByKeyResponse")]
        Test.ServiceReference1.JSON_OBJ GetObjectByKey(string Key, int ObjType, string SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/GetObjectByKey", ReplyAction="http://tempuri.org/IComModelService/GetObjectByKeyResponse")]
        System.Threading.Tasks.Task<Test.ServiceReference1.JSON_OBJ> GetObjectByKeyAsync(string Key, int ObjType, string SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/AddUpdateObject", ReplyAction="http://tempuri.org/IComModelService/AddUpdateObjectResponse")]
        Test.ServiceReference1.Response AddUpdateObject(Test.ServiceReference1.JSON_OBJ Object, string SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/AddUpdateObject", ReplyAction="http://tempuri.org/IComModelService/AddUpdateObjectResponse")]
        System.Threading.Tasks.Task<Test.ServiceReference1.Response> AddUpdateObjectAsync(Test.ServiceReference1.JSON_OBJ Object, string SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/LogOut", ReplyAction="http://tempuri.org/IComModelService/LogOutResponse")]
        void LogOut(string SessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IComModelService/LogOut", ReplyAction="http://tempuri.org/IComModelService/LogOutResponse")]
        System.Threading.Tasks.Task LogOutAsync(string SessionID);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        public LoginRequest() {
        }
        
        public LoginRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string SessionID;
        
        public LoginResponse() {
        }
        
        public LoginResponse(string Message, string SessionID) {
            this.Message = Message;
            this.SessionID = SessionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SignIn", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SignInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        public SignInRequest() {
        }
        
        public SignInRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SignInResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SignInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string SessionID;
        
        public SignInResponse() {
        }
        
        public SignInResponse(string Message, string SessionID) {
            this.Message = Message;
            this.SessionID = SessionID;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IComModelServiceChannel : Test.ServiceReference1.IComModelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComModelServiceClient : System.ServiceModel.ClientBase<Test.ServiceReference1.IComModelService>, Test.ServiceReference1.IComModelService {
        
        public ComModelServiceClient() {
        }
        
        public ComModelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ComModelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComModelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ComModelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.ServiceReference1.LoginResponse Test.ServiceReference1.IComModelService.Login(Test.ServiceReference1.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string username, string password, out string SessionID) {
            Test.ServiceReference1.LoginRequest inValue = new Test.ServiceReference1.LoginRequest();
            inValue.username = username;
            inValue.password = password;
            Test.ServiceReference1.LoginResponse retVal = ((Test.ServiceReference1.IComModelService)(this)).Login(inValue);
            SessionID = retVal.SessionID;
            return retVal.Message;
        }
        
        public System.Threading.Tasks.Task<Test.ServiceReference1.LoginResponse> LoginAsync(Test.ServiceReference1.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.ServiceReference1.SignInResponse Test.ServiceReference1.IComModelService.SignIn(Test.ServiceReference1.SignInRequest request) {
            return base.Channel.SignIn(request);
        }
        
        public string SignIn(string username, string password, out string SessionID) {
            Test.ServiceReference1.SignInRequest inValue = new Test.ServiceReference1.SignInRequest();
            inValue.username = username;
            inValue.password = password;
            Test.ServiceReference1.SignInResponse retVal = ((Test.ServiceReference1.IComModelService)(this)).SignIn(inValue);
            SessionID = retVal.SessionID;
            return retVal.Message;
        }
        
        public System.Threading.Tasks.Task<Test.ServiceReference1.SignInResponse> SignInAsync(Test.ServiceReference1.SignInRequest request) {
            return base.Channel.SignInAsync(request);
        }
        
        public Test.ServiceReference1.JSON_OBJ GetObjectByKey(string Key, int ObjType, string SessionID) {
            return base.Channel.GetObjectByKey(Key, ObjType, SessionID);
        }
        
        public System.Threading.Tasks.Task<Test.ServiceReference1.JSON_OBJ> GetObjectByKeyAsync(string Key, int ObjType, string SessionID) {
            return base.Channel.GetObjectByKeyAsync(Key, ObjType, SessionID);
        }
        
        public Test.ServiceReference1.Response AddUpdateObject(Test.ServiceReference1.JSON_OBJ Object, string SessionID) {
            return base.Channel.AddUpdateObject(Object, SessionID);
        }
        
        public System.Threading.Tasks.Task<Test.ServiceReference1.Response> AddUpdateObjectAsync(Test.ServiceReference1.JSON_OBJ Object, string SessionID) {
            return base.Channel.AddUpdateObjectAsync(Object, SessionID);
        }
        
        public void LogOut(string SessionID) {
            base.Channel.LogOut(SessionID);
        }
        
        public System.Threading.Tasks.Task LogOutAsync(string SessionID) {
            return base.Channel.LogOutAsync(SessionID);
        }
    }
}
